import { theme } from "@/styled/theme";
import "@/styled/reset.css";
import type { AppProps } from "next/app";
import { ThemeProvider } from "styled-components";
import Head from "next/head";

function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Camplify :: Rv Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://d2twadweelp7yv.cloudfront.net/assets/camplify-rv-logo-transparent-efd21c6115b9431e87fe5e6d89d82695c04de7e9544d087dff632caf17288a15.png"
        />
      </Head>
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

export default App;
